export declare const ALEF = "\u0627";
export declare const ALEF_MADDA = "\u0622";
export declare const ALEF_HAMZA_ABOVE = "\u0623";
export declare const ALEF_HAMZA_BELOW = "\u0625";
export declare const ALEF_WASLA = "\u0671";
export declare const ALEF_MAQSURA = "\u0649";
export declare const HAMZA = "\u0621";
export declare const WAW_HAMZA = "\u0624";
export declare const YA_HAMZA = "\u0626";
export declare const HAMZA_LETTERS: Set<string>;
export declare const IDGHAM_HOMORGANIC_PAIRS: Set<string>;
export declare const FATHATAN = "\u064B";
export declare const DAMMATAN = "\u064C";
export declare const KASRATAN = "\u064D";
export declare const FATHA = "\u064E";
export declare const DAMMA = "\u064F";
export declare const KASRA = "\u0650";
export declare const SHADDA = "\u0651";
export declare const SUKUN = "\u0652";
export declare const SMALL_KASRA = "\u06EA";
export declare const MADDAH = "\u0653";
export declare const HAMZA_ABOVE = "\u0654";
export declare const HAMZA_BELOW = "\u0655";
export declare const DAGGER_ALEF = "\u0670";
export declare const SMALL_WAW = "\u06E5";
export declare const SMALL_YA = "\u06E6";
export declare const TATWEEL = "\u0640";
export declare const BOM = "\uFEFF";
export declare const DIACRITICS: Set<string>;
export declare const STOP_SIGNS: Set<string>;
export declare const IGNORABLE: Set<string>;
export declare const ALEF_CARRIERS: Set<string>;
export declare const SUN_LETTERS: Set<string>;
export declare const LETTER_TO_SYMBOL: Record<string, string>;
export declare const QALQALAH: Set<string>;
export declare const VOWELS: Set<string>;
//# sourceMappingURL=arabic.d.ts.map